owner: Donut-Insights
repo: misafirmind-upptime

sites:
  - name: orchestrator
    url: https://api.misafirmind.com/messorch/actuator/health
  - name: chat
    url: https://api.misafirmind.com/chatflow/health
  - name: llm
    url: https://api.misafirmind.com/agentflow/health
  - name: dashboard
    url: https://api.misafirmind.com/maestro/health
  - name: go
    url: https://api.misafirmind.com/go/health
  - name: survey
    url: https://api.misafirmind.com/survey/health

status-website:
  cname: status.misafirmind.com
  logoUrl: https://framerusercontent.com/images/jfep2ZE5uCpTziweWhE0S7jeg.png?scale-down-to=512
  name: " "
  introTitle: "Live status of **misafirmind** services"
  introMessage: "All checks are automated and updated in real time."
  themeUrl: https://status.misafirmind.com/white-theme.css
  favicon: https://framerusercontent.com/avatars/teams/efb2dbfc-ba09-4482-8d02-2d6d55cbcb57/RoUPMPrVE
  customHeadHtml: '<title>status | misafirmind</title>'
  i18n:
    footer: ""

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/30 * * * *"
