# Change these first
owner: Donut-Insights # Your GitHub organization or username, where this repository lives
repo: misafirmind-upptime # The name of this repository

sites:
  - name: misafirmind-survey
    url: https://api.misafirmind.com/survey/health


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.misafirmind.com
  #baseUrl: /
  logoUrl: https://framerusercontent.com/images/jfep2ZE5uCpTziweWhE0S7jeg.png?scale-down-to=512
  name: misafirmind
  introTitle: "**misafirmind** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Monitor the live status of misafirmind infrastructure and services. All checks are automated and updated in real time."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
