owner: Donut-Insights
repo: misafirmind-upptime

sites:
  - name: message-orchestrator
    url: https://api.misafirmind.com/messorch/actuator/health
  - name: survey
    url: https://api.misafirmind.com/survey/health
    
status-website:
  cname: status.misafirmind.com
  logoUrl: https://framerusercontent.com/images/jfep2ZE5uCpTziweWhE0S7jeg.png?scale-down-to=512
  name: " "
  introTitle: "Live status of **misafirmind** services"
  introMessage: "All checks are automated and updated in real time."
  themeUrl: https://status.misafirmind.com/white-theme.css
  i18n:
    footer: ""
